services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack endpoint
    environment:
      - DEBUG=1
      - DYNAMODB_SHARE_DB=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "$PWD/init-dynamodb.sh:/etc/localstack/init/ready.d/init-dynamodb.sh" # Initialization script
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"